# Generated by Django 3.2.4 on 2021-09-06 13:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('label', models.CharField(max_length=32)),
                ('flagged_high', models.IntegerField()),
                ('version', models.CharField(max_length=12)),
                ('wifisignal', models.CharField(max_length=12)),
                ('pm2_5value', models.CharField(max_length=8)),
                ('pm2_5_1hour', models.FloatField()),
                ('pm2_5_24hour', models.FloatField()),
                ('pm2_5_1week', models.FloatField()),
                ('sensordiff', models.CharField(max_length=8)),
                ('aqi', models.IntegerField()),
                ('aqitext', models.CharField(max_length=48)),
                ('aqi1hour', models.IntegerField()),
                ('aqi1hourtext', models.CharField(max_length=48)),
                ('aqi24hour', models.IntegerField()),
                ('aqi24hourtext', models.CharField(max_length=48)),
                ('aqi1week', models.IntegerField()),
                ('aqi1weektext', models.CharField(max_length=48)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
