# Generated by Django 3.2.4 on 2021-09-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='aqi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqi1hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqi1hourtext',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqi1week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqi1weektext',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqi24hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqi24hourtext',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='aqitext',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='flagged_high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='label',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='pm2_5_1hour',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='pm2_5_1week',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='pm2_5_24hour',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='pm2_5value',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='sensordiff',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='site_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='version',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='wifisignal',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
