# Generated by Django 3.2.7 on 2021-10-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastRadonTest',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastVist',
            field=models.DateField(),
        ),
    ]
